### ISSUE TITLE
Build -> Delombok project does not work on Linux

### ISSUE THREAD

**Issue by arshdefoamed** [04637/delombok#8]
OS: RHEL 8 

While trying to delombok project. Following error is displayed 

> ==>start: /<path>/WorkBench/src
> 	==>copy: from /<path>/WorkBench/src to /<path>WorkBench/delombok/src-bak
> 	==>delombok...
> ==>failed: Cannot run program "cmd" (in directory "/<path>/WorkBench"): error=2, No such file or directory

**Comment by jiguantong** [comment]
@arshdefoamed  Thank you for your feedback💕. I added Linux support to the v1.18.4.5 version🎉. You can download and install it from here, or you will be able to get the latest version from the Jetbrains plugin market in two days (because Jetbrains needs to review it).
[delombok.zip](https://github.com/04637/delombok/files/7769085/delombok.zip)
